/** Do not edit directly. Generated by scripts/build-player-themes.mjs. */
export const PLAYER_THEME_DEFINITIONS = [
  {
    id: "forest",
    name: "Лес",
    colorScheme: "dark",
    version: 1,
  },
  {
    id: "dragons",
    name: "Драконы",
    colorScheme: "dark",
    version: 1,
  },
  {
    id: "ice",
    name: "Лёд",
    colorScheme: "dark",
    version: 1,
  },
  {
    id: "fire",
    name: "Огонь",
    colorScheme: "dark",
    version: 1,
  },
  {
    id: "gold",
    name: "Золото",
    colorScheme: "dark",
    version: 1,
  },
  {
    id: "silver",
    name: "Серебро",
    colorScheme: "dark",
    version: 1,
  },
  {
    id: "light",
    name: "Светлая",
    colorScheme: "light",
    version: 1,
  },
  {
    id: "classic-v1",
    name: "Прежнее оформление",
    colorScheme: "dark",
    version: 1,
  },
] as const;
