-- Build the count query from the checked-in allowlist and only the tables that
-- exist in the live database. This lets a candidate checkout back up an older
-- (valid migration-prefix) production database without referencing future
-- tables. The restore report records sampled versus full coverage.
SELECT string_agg(
  format(
    'SELECT %L AS table_name, count(*)::bigint AS row_count FROM %I',
    table_name,
    table_name
  ),
  E'\nUNION ALL\n'
) || E'\nORDER BY 1;'
FROM (
  VALUES
    ('account_action_tokens'),
    ('account_campaign_creations'),
    ('account_campaign_invites'),
    ('account_mail_outbox'),
    ('account_sessions'),
    ('action_journal'),
    ('assets'),
    ('campaign_audio_tracks'),
    ('campaign_sound_packs'),
    ('campaign_soundpad_settings'),
    ('campaign_sounds'),
    ('campaigns'),
    ('catalog_entries'),
    ('character_catalog_entries'),
    ('character_controllers'),
    ('character_media'),
    ('character_spell_assignment_versions'),
    ('character_spell_assignments'),
    ('characters'),
    ('chat_attachment_uploads'),
    ('chat_attachments'),
    ('chat_messages'),
    ('chat_read_cursors'),
    ('chat_threads'),
    ('drawings'),
    ('encounters'),
    ('feedback_attachments'),
    ('feedback_operator_audits'),
    ('feedback_reports'),
    ('fog_reveals'),
    ('game_events'),
    ('global_sticker_media'),
    ('global_sticker_packs'),
    ('global_stickers'),
    ('gm_access_credentials'),
    ('invites'),
    ('memberships'),
    ('player_access_grants'),
    ('player_likeness_consents'),
    ('player_requests'),
    ('public_roadmap_votes'),
    ('scenes'),
    ('sessions'),
    ('spell_pack_versions'),
    ('spell_packs'),
    ('sticker_media'),
    ('sticker_pack_entitlements'),
    ('sticker_packs'),
    ('stickers'),
    ('story_import_batches'),
    ('story_import_sources'),
    ('story_post_media'),
    ('story_post_revisions'),
    ('story_posts'),
    ('token_controllers'),
    ('token_definitions'),
    ('tokens'),
    ('users'),
    ('world_content'),
    ('world_content_actions'),
    ('world_content_instance_actions'),
    ('world_content_instances'),
    ('world_content_media'),
    ('world_content_relations'),
    ('world_map_location_scenes'),
    ('world_map_locations'),
    ('world_map_party_position'),
    ('world_maps')
) AS allowlist(table_name)
WHERE to_regclass(format('%I.%I', 'public', table_name)) IS NOT NULL
\gexec
